import * as Yup from "yup";

export const createPersonaInitialValues = {
  name: "",
  personaPrompt: "",
  files: [],
};

export const updatePersonaInitialValues = {
  id: "",
  name: "",
  persona_name: "",
  age: "",
  gender: "",
  occupation: "",
  language: "",
  hometown: "",
  birthdate: "",
  nationality: "",
  background: "",
  scenarioSnippet: "",
  mbtiType: "",
  enneagramType: "",
  openness: "",
  conscientiousness: "",
  extraversion: "",
  agreeableness: "",
  neuroticism: "",
  skillsAndAbilities: "",
  motivationsAndGoals: "",
  build: "",
  height: "",
  eyeColor: "",
  skinTone: "",
  hairColor: "",
  hairStyle: "",
  typicalAttire: "",
  distinguishingFeatures: "",
  industryRelevance: "",
  relevanceToScenario: "",
  challengesAndGrowthAreas: "",
};

export const createPersonaSchema = Yup.object({
  name: Yup.string().required(),
  personaPrompt: Yup.string().required(),
});

export const updatePersonaSchema = Yup.object({
  persona_name: Yup.string().required(),
  age: Yup.string().required(),
  gender: Yup.string().required(),
  occupation: Yup.string().required(),
  language: Yup.string().required(),
  hometown: Yup.string().required(),
  birthdate: Yup.string().required(),
  nationality: Yup.string().required(),
  background: Yup.string().required(),
  scenarioSnippet: Yup.string().required(),
  mbtiType: Yup.string().required(),
  enneagramType: Yup.string().required(),
  openness: Yup.string().required(),
  conscientiousness: Yup.string().required(),
  extraversion: Yup.string().required(),
  agreeableness: Yup.string().required(),
  neuroticism: Yup.string().required(),
  skillsAndAbilities: Yup.string().required(),
  motivationsAndGoals: Yup.string().required(),
  build: Yup.string().required(),
  height: Yup.string().required(),
  eyeColor: Yup.string().required(),
  skinTone: Yup.string().required(),
  hairColor: Yup.string().required(),
  hairStyle: Yup.string().required(),
  typicalAttire: Yup.string().required(),
  distinguishingFeatures: Yup.string().required(),
  industryRelevance: Yup.string().required(),
  relevanceToScenario: Yup.string().required(),
  challengesAndGrowthAreas: Yup.string().required(),
});
