export const createPersonaInitialValues = {
  name: "",
  personaPrompt: "",
  files: [],
};

export const updatePersonaInitialValues = {
  id: "",
  name: "",
  persona_name: "",
  age: "",
  gender: "",
  occupation: "",
  language: "",
  hometown: "",
  birthdate: "",
  nationality: "",
  background: "",
  scenarioSnippet: "",
  mbtiType: "",
  enneagramType: "",
  openness: "",
  conscientiousness: "",
  extraversion: "",
  agreeableness: "",
  neuroticism: "",
  skillsAndAbilities: "",
  motivationsAndGoals: "",
  build: "",
  height: "",
  eyeColor: "",
  skinTone: "",
  hairColor: "",
  hairStyle: "",
  typicalAttire: "",
  distinguishingFeatures: "",
  industryRelevance: "",
  relevanceToScenario: "",
  challengesAndGrowthAreas: "",
};

export const createRubricInitialValues = {
  name: "",
  description: "",
  files: [],
};
